load_mac("ga/packages.mac")$
load_mac("test.mac")$

suite:test_suite_begin("Test ecosystem",[])$

population:[]$
for i:1 thru 10 do block(
  population:append(
    population,
    [ga_chromosome_new([[1,1]],[10,100.0])]))$

test_target(e,c):=0.01/(0.01 + c@fitness:c@matrixes[1][1,1] ^ 2);

ecosystem:new(
  ga_ecosystem(
    target:test_target,
    population:population,
    best:[],
    max_generations:100,
    crossover_ratio:0.8,
    mutation_ratio:0.01))$

test_suite_log(
  suite,
  "Logging ecosystem ...")$

test_suite_log(
  suite,
  ecosystem)$

test_suite_log(
  suite,
  "Logging ecosystem done.")$

test_suite_log(
  suite,
  "Logging generations results 100 times ...")$

for i:1 step 1 thru 100 do block(
  ga_ecosystem_next_generation(ecosystem),
  test_suite_log(
    suite,
    concat("Generations:",i)),
  test_suite_log(
    suite,
    ecosystem@best@fitness))$

test_suite_log(
  suite,
  "Logging generations results 10 times done.")$

test_suite_log(
    suite,
    ecosystem)$

test_suite_end(suite)$
