test_assert_equal(a,b,message)::= if is(a=b) then test_trace("SUCCESSED:",message) else test_trace("FAILED:",message)$
test_assert_true(a,message)::=if is(a) then test_trace("SUCCESSED:",message) else test_trace("FAILED:",message)$
test_assert_false(a,message)::=if is(not a) then test_trace("SUCCESSED:",message) else test_trace("FAILED:",message)$
test_assert_not_equal(a,b,message)::= if is(a#b) then test_trace("SUCCESSED:",message) else test_trace("FAILED:",message)$