/*compute partial derivative
 *@param f the function
 *@param l a list contains variants
 *@return a list contains partial derivative of function 'f'
**/
ldiff(f,l):= 
    maplist(
        lambda([x],
            diff(f,x)),v);

/*compute partial derivative
*@param f the functions
*@param v a metrix contains variants
*@return a list contains partial derivative of function 'f'
*/
mdiff(f,v):=
    matrixmap(
        lambda([x],
            diff(f,x)),m);

