load_mac("bfgs/test.mac")$

suite:test_suite_begin("Test bfgs_gradient",[])$

test_suite_log(suite,"Test bfgs_gradient.")$

case:test_case_begin(suite,"Test bfgs_gradient",[])$
test_case_run(
  case,
  block(
    [func,grad],
    test_case_log(case,"Logging in ."),
    func:x^2 + 2 * y,
    test_case_log(case,"target function:"),
    test_case_log(case,func),
    test_case_assert_equal(
      case,
      "bfgs_gradient result assertion.",
      [2*x,2],
      bfgs_gradient(func,[x,y]))))$

test_case_end(case)$

test_suite_end(suite)$
