load_mac("nn/packages.mac")$
load_mac("test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("Test bpnn_evaluate",[])$

test_suite_log(suite,"Test functions in the BPNN.")$
bpnn:[]$
nn_outputs:[]$

case:test_case_begin(suite,"Test bpnn_new",[])$
test_case_run(
  case,
  test_case_log(_case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer,transfer],
    total_error),
  test_case_log(case,bpnn),
  
  result:bpnn_evaluate(bpnn,bpnn@symbol_matrixes),
  test_case_assert_equal(
    case,
    "Evaluate value Equal.",
    result,
    bpnn@numeric_matrixes))$
test_case_end(case)$

test_suite_end(suite)$