load_mac("nn/packages.mac")$
load_mac("test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("Test bpnn_solve_lms",[])$

test_suite_log(suite,"Test functions in the BPNN.")$
bpnn:[]$
nn_outputs:[]$

case:test_case_begin(suite,"Test bpnn_solve_lms",[])$
test_case_run(
  case,
  test_case_log(_case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer,transfer],
    total_error),
  test_case_log(case,bpnn),
  
  result:bpnn_solve_lms(bpnn,inputs,outputs,100),
  test_case_log(case,"LMS solver result."),
  test_case_log(case,bpnn),
test_case_end(case)$

test_suite_end(suite)$