load_mac("nn/packages.mac")$
load_mac("test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("BPNN bpnn_caculate_symbol_output",[])$

test_suite_log(suite,"Test bpnn_caculate_symbol_output")$
bpnn:[]$
nn_outputs:[]$

bpnn_output_case:test_case_begin(suite,"Test bpnn_caculate_symbol_output.",[])$
test_case_run(
  bpnn_output_case,
  test_case_log(bpnn_output_case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer,transfer],
    total_error),
  test_case_log(bpnn_output_case,bpnn),
  test_case_log(bpnn_output_case,"Input values."),
  nn_outputs:maplist(
    lambda(
      [input],
      test_case_log(bpnn_output_case,"Logging input value:"),
      test_case_log(bpnn_output_case,input),
      output:bpnn_caculate_symbol_output(bpnn,input),
      test_case_log(bpnn_output_case,"Logging output value"),
      test_case_log(bpnn_output_case,output),
      test_case_assert_equal(
        bpnn_output_case,
        "Output size",
        [1,2],
        matrix_size(output)),
      output),
    inputs))$
test_case_end(bpnn_output_case)$

test_suite_end(suite)$