load_mac("nn/test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("Test bpnn_evaluate",[])$

test_suite_log(suite,"Test functions in the BPNN.")$
bpnn:[]$
nn_outputs:[]$

case:test_case_begin(suite,"Test bpnn_new",[])$
test_case_run(
  case,
  test_case_log(_case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer,transfer],
    total_error),
  test_case_log(case,bpnn),
  
  maplist(
    lambda(
      [input],
      output:bpnn_caculate_numeric_output(bpnn,inputs[1]),
      test_case_log(case,"Logging numeric output:"),
      test_case_log(case,output)),
    inputs))$
    
test_case_end(case)$

test_suite_end(suite)$