load_mac("nn/packages.mac")$
load_mac("test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("BPNN Test Suite",[])$

test_suite_log(suite,"Test functions in the BPNN.")$
bpnn:[]$
nn_outputs:[]$

case:test_case_begin(suite,"Test bpnn_caculate_symbol_error.",[])$
test_case_run(
  case,
  test_case_log(case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer,transfer],
    total_error),
  test_case_log(case,bpnn),
  maplist(
    lambda(
      [input,output],
      test_case_log(case,"Logging input value:"),
      test_case_log(case,input),
      test_case_log(case,"Logging output value"),
      test_case_log(case,output)),
    inputs,
    outputs),
  
  test_case_log(case,"Loging error value"),
  test_case_log(
    case,
    bpnn_caculate_symbol_error(bpnn,inputs,outputs)))$
test_case_end(case)$

test_suite_end(suite)$