load_mac("lcp/test.mac")$

suite:test_suite_begin("bcp_min_index suite",[])$

test_suite_log(suite,"Testing bcp_min_index...")$

case:test_case_begin(suite,"bcp_min_index case",[])$

test_case_run(
  case,
  block(
    [list],
    list:[2,1,3],
    test_case_log(case,"test list:"),
    test_case_log(case,list),
    test_case_assume_equal(case,
      "bcp_min_index result",
      2,
      lcp_min_index(list))))$

test_case_end(case)$

test_suite_log(suite,"Testing bcp_min_index done.")$
test_suite_end(suite)$
