load_mac("lcp/test.mac")$

suite:test_suite_begin("Test lcp_solve",[])$

test_suite_log(suite,"Testing lcp_solve...")$

case:test_case_begin(suite,"solve case",[])$

test_case_run(
  case,
  block(
    [testM,testQ,input,excepted,output],
    testM:matrix(
      [1,1,3,4],
      [5,3,1,1],
      [2,1,2,0],
      [1,4,1,1]),
    testQ:transpose([-1,2,-1,-3]),
    test_case_log(case,"M:"),
    test_case_log(case,testM),
    test_case_log(case,"q:"),
    test_case_log(case,testQ),
    input:new(lcp_input(M:testM,q:testQ)),
    test_case_log(case,"Input:"),
    test_case_log(case,input),
    excepted:new(
      lcp_output(
        v:transpose([21/2,5,0,0]),
        p:transpose([0,0,1/2,5/2]))),
    output:lcp_solve(input),
    test_case_assume_equal(case,
      "Verify solve result",
      excepted,
      output)))$
test_case_end(case)$

test_suite_log(suite,"Testing lcp_solve done.")$
test_suite_end(suite)$
