load_mac("qp/test.mac")$

suite:test_suite_begin("test qp_lcp",[])$
test_suite_log(suite,"Testing qp_lcp...")$

case:test_case_begin(suite,"Test Case for qp_lcp",[])$

test_case_run(
  case,
  test_case_log(case,"no test input supplied now"),
  test_case_assert_inclusive(case,"Inclusive Assertion")  
/*
test_case_assume_equal(case,"Pass Assume Equal",1,1),
test_case_assume_not_equal(case,"Pass Assume Not Equal",1,3),
test_case_assert_equal(case,"Pass Assert Equal",1,1),
test_case_assert_not_equal(case,"Pass Assert Not Equal",1,3)
*/
)$

test_case_end(case)$

test_suite_log(suite,"Testing qp_lcp done.")$
test_suite_end(suite)$
