load_mac("XXX/test.mac")$

suite:test_suite_begin("Test Suite SuiteXXX",[])$

test_suite_log(suite,"Loging something.")$

case:test_case_begin(suite,"Test Case CaseYYY",[])$

test_case_run(
  case,
  test_case_log(case,"Logging in test case."),
  test_case_assume_equal(case,"Pass Assume Equal",1,1),
  test_case_assume_not_equal(case,"Pass Assume Not Equal",1,3),
  test_case_assert_equal(case,"Pass Assert Equal",1,1),
  test_case_assert_not_equal(case,"Pass Assert Not Equal",1,3))$

test_case_end(case)$

test_suite_end(suite)$
