load_mac("matrix/test.mac")$

suite:test_suite_begin("matrix_col_multiple",[])$
test_suite_log(suite,"Testing matrix_col_multiple...")$

case:test_case_begin(suite,"matrix_col_multiple",[])$

test_case_run(
  case,
  block(
    [mat],
    mat:matrix([1,2,3,4],[1,2,3,4],[2,3,4,5],[7,8,9,0]),
    test_case_log(case,"Test Matrix:"),
    test_case_log(case,mat),
    test_case_assume_equal(
      case,
      "Matrix Column 2 multiple -1:",
      matrix([1,-2,3,4],[1,-2,3,4],[2,-3,4,5],[7,-8,9,0]),
      matrix_col_multiple(mat,-1,2))))$

test_case_end(case)$

test_suite_log(suite,"Testing matrix_col_multiple done.")$
test_suite_end(suite)$
