load_mac("matrix/test.mac")$

suite:test_suite_begin("matrix_col_switch",[])$
test_suite_log(suite,"Testing matrix_col_switch...")$

case:test_case_begin(suite,"matrix_col_switch",[])$

test_case_run(
  case,
  block(
    [mat],
    mat:matrix([1,2,3,4],[1,2,3,4],[2,3,4,5],[7,8,9,0]),
    test_case_log(case,"Test Matrix:"),
    test_case_log(case,mat),
    test_case_assume_equal(
      case,
      "Matrix switch Column 1 and 3:",
      matrix([4,2,3,1],[4,2,3,1],[5,3,4,2],[0,8,9,7]),
      matrix_col_switch(mat,1,4))))$

test_case_end(case)$

test_suite_log(suite,"Testing matrix_col_switch done.")$
test_suite_end(suite)$
