load_mac("nn/packages.mac")$
load_mac("test.mac")$

load_mac("nn/test/data.mac")$

suite:test_suite_begin("BPNN Test Suite",[])$

test_suite_log(suite,"Test functions in the BPNN.")$
bpnn:[]$
bpnn_create_case:test_case_begin(suite,"Test bpnn_new",[])$
test_case_run(
  bpnn_create_case,
  test_case_log(bpnn_create_case,"Transfer function value at 1"),
  test_case_log(bpnn_create_case,transfer_function(1)),
  test_case_log(bpnn_create_case,"create BPNN."),
  bpnn:bpnn_new(
    dims,
    hides,
    [transfer_function,transfer_function],
    error_function),
  test_case_log(bpnn_create_case,bpnn),
  test_case_assert_not_equal(
    bpnn_create_case,
    "Created a BPNN structure",
    bpnn,
    []))$
test_case_end(bpnn_create_case)$

if not is(bpnn=[]) then block(
  bpnn_output_case:test_case_begin(suite,"Test bpnn_caculate_symbol_output.",[]),
  test_case_run(
    bpnn_output_case,
    test_case_log(bpnn_output_case,"Input values."),
    outputs:maplist(
      lambda(
        [input],
        test_case_log(bpnn_output_case,"Logging input value:"),
        test_case_log(bpnn_output_case,input),
        output:bpnn_caculate_symbol_output(bpnn,input),
        test_case_log(bpnn_output_case,"Logging output value"),
        test_case_log(bpnn_output_case,output)),
      inputs)),
  test_case_end(bpnn_output_case),
  
  bpnn_error_case:test_case_begin(suite,"Test bpnn_caculate_symbol_error.",[]),
  test_case_run(
    bpnn_error_case,
    test_case_log(bpnn_error_case,"error."),
    test_case_log(bpnn_error_case,error_function([1,1],[1,1])),
    outputs:maplist(
      lambda(
        [input,output],
        test_case_log(bpnn_error_case,"Logging input value:"),
        test_case_log(bpnn_error_case,input),
        test_case_log(bpnn_error_case,"Logging output value"),
        test_case_log(bpnn_error_case,output),
        test_case_log(bpnn_error_case,"Loging error value"),
        test_case_log(bpnn_error_case,
          bpnn_caculate_symbol_error(bpnn,input,output))),
      inputs,
      outputs)),
  test_case_end(bpnn_error_case))$

test_suite_end(suite)$