inputs:[
[0.1,0.1]];
/*
[0.2,0.2],
[0.3,0.3]];
*/
outputs:[
[0.2,0.2]];
/*
[0.3,0.3],
[0.4,0.4]];
*/

hides:[h1,h2];

dims:[2,3,2];

transfer(x):=(1-exp(-x))/(1+exp(-x));

total_error(results,excepted):=block(
  [total,list],
  list:maplist(
    lambda(
      [x,y],
      if listp(x) then x:matrix(x),
      if listp(y) then y:matrix(y),
      (x-y) . (x-y)),
    results,
    excepted),
  total:sum(list[i],i,1,length(list)),
  sqrt(total));
